language: node_js
node_js:
  - "0.12"

branches:
  only:
    - master

addons:
  ssh_known_hosts:
  - github.com

before_install:
  - git config --global user.name "panjiabang"
  - git config --global user.email panjiabang@gmail.com

install:
  - npm install -g tiddlywiki

script:
  - tiddlywiki . --build index
  - cp .travis/CNAME ./output/
  - cp .travis/favicon.png ./output/favicon.ico
  - git checkout --orphan gh-pages
  - ls | grep -v output | xargs rm -rf
  - cp -a ./output/* ./
  - rm -rf ./output && rm -rf .travis*
  - git add --all
  - git commit -m "$(curl -s whatthecommit.com/index.txt || echo no comment)"
  - git push -f -q "https://JamesPan:${GH_TOKEN}@${GH_REF}" gh-pages:gh-pages > /dev/null 2>&1
