language: node_js
node_js:
  - "0.12"

branches:
  only:
    - master

addons:
  ssh_known_hosts:
  - github.com

before_install:
  - git config --global user.name "panjiabang"
  - git config --global user.email panjiabang@gmail.com

install:
  - npm install -g tiddlywiki

script:
  - tiddlywiki . --rendertiddler $:/core/save/all ./index.html text/plain
  - cp .travis/CNAME ./output/
  - cp .travis/favicon.png ./output/
  - git checkout -b gh-pages
  - cp -a ./output/* ./
  - rm -rf ./output
  - git add --all
  - git commit -m "$(curl -s whatthecommit.com/index.txt || echo no comment)"
  - git push -f -q "https://JamesPan:${GH_TOKEN}@${GH_REF}" gh-pages:gh-pages &2>/dev/null
